# This is a basic workflow to help you get started with Actions

name: konnect

on:
  workflow_dispatch:
  
jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

          
      - name: Install Insomnia
        run: |
          wget https://github.com/Kong/insomnia/releases/download/lib%408.6.1/inso-linux-8.6.1.tar.xz
          tar -xf inso-linux-8.6.1.tar.xz 
          sudo cp inso /usr/local/bin/
          ls
          
      - name: Run API Tests
        id: apiTests
        run: ./inso --src ./insomnia/Insomnia_2024-03-13.json run test spc_3c9d47
          
        

